version: "3.7"

services:
  # Composer
  composer:
    image: composer
    volumes:
      - .:/app:z
      # Map local user Composer directory with container for cache packages
      - ~/.docker_cache/composer:/tmp/cache:z
    working_dir: /app

volumes:
  mysql_data:
    name: laraveltest_mysql_data
